# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44726bdcf12e0dc9d6b49c57c6f0ab741a089ab5549873f1ca1eeed51f36a5449d2fe7eb039a02e57de9a58ce721815a112939cc0c23b33914731d27e9e1a08d

test:
  secret_key_base: 97a780ea8d27faa65562ad72c631afff84ef1173ee9523de9cd57bb67ad1b380aec171a41c75fbbe07a7b88146c98e704e730ce9d37f983ce4fb97d5adeb89fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
